using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ColonyMaster.Entities
{
    /// <summary>
    /// Invoice detail line.
    /// </summary>
    public class InvoiceDetail
    {
        [Key]
        public Guid Id { get; private set; } = Guid.NewGuid();

        [Required]
        public Guid InvoiceId { get; private set; }

        [ForeignKey(nameof(InvoiceId))]
        public Invoice? Invoice { get; private set; }

        public string? Description { get; private set; }

        public decimal Quantity { get; private set; }

        [Column(TypeName = "decimal(18,2)")]
        public decimal UnitPrice { get; private set; }

        [Column(TypeName = "decimal(18,2)")]
        public decimal Total { get; private set; }


        public InvoiceDetail() { }

        /// <summary>
        /// Create a new invoice detail with autogenerated Id.
        /// </summary>
        public InvoiceDetail(Guid invoiceId, string? description, decimal quantity, decimal unitPrice)
        {
            Id = Guid.NewGuid();
            Update(description, quantity, unitPrice);
            InvoiceId = invoiceId;
        }

        /// <summary>
        /// Create an invoice detail preserving a specific Id (used for updates).
        /// </summary>
        public InvoiceDetail(Guid id, Guid invoiceId, string? description, decimal quantity, decimal unitPrice)
        {
            Id = id == Guid.Empty ? Guid.NewGuid() : id;
            InvoiceId = invoiceId;
            Update(description, quantity, unitPrice);
        }

        /// <summary>
        /// Update the detail line values and recompute the total.
        /// </summary>
        public void Update(string? description, decimal quantity, decimal unitPrice)
        {
            Description = description;
            Quantity = quantity;
            UnitPrice = unitPrice;
            Total = quantity * unitPrice;
        }
    }
}
